on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: build ${{ matrix.platform.name }}
    if: startsWith(github.event.head_commit.message, 'v')
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            name: linux-x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            name: linux-arm64
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            name: macos-x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            name: macos-arm64
            target: aarch64-apple-darwin
          - os: windows-latest
            name: windows-x86_64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            name: windows-arm64
            target: aarch64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          toolchain: stable
          command: build
          args: --locked --release

      - name: Package
        if: matrix.platform.os != 'windows-latest'
        run: |
          mkdir -p dist
          bin_name="wheel-picker"
          cp target/${{ matrix.platform.target }}/release/${bin_name} dist/
          cd dist
          zip ../${{ matrix.platform.name }}.zip ${bin_name}

      - name: Package (Windows)
        if: matrix.platform.os == 'windows-latest'
        run: |
          mkdir dist
          $bin_name = "wheel-picker.exe"
          Copy-Item "target/${{ matrix.platform.target }}/release/$bin_name" dist/
          Compress-Archive -Path "dist/$bin_name" -DestinationPath "${{ matrix.platform.name }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ matrix.platform.name }}.zip

  release:
    if: startsWith(github.event.head_commit.message, 'v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Get commit version and body
        id: commit
        run: |
          full_msg='${{ github.event.head_commit.message }}'
          version_num="$(echo "$full_msg" | head -n1)"
          body="$(echo "$full_msg" | tail -n +2)"

          {
            echo "version_num<<EOF"
            echo "${version_num:1}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          {
            echo "body<<EOF"
            echo "$body"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.commit.outputs.version_num }}
          body: |
            [crates.io release](https://crates.io/crates/wheel-picker/${{ steps.commit.outputs.version_num }})

            ${{ steps.commit.outputs.body }}
          files: dist/**/*.zip

  publish:
    if: startsWith(github.event.head_commit.message, 'v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
